configuration: 
  name: bioqa-development-test
  author: yanfang

persistence-provider:
  inherit: bioqa.persistence.remote-persistence-provider
  
async-configuration:
  inherit: bioqa.async.cse-broker

collection-reader:
  inherit: bioqa.collection.db-collection-reader-producer
  dataset: BIO-COMBINED
  sequence-start: 160
  sequence-end: 187

pipeline:
  - inherit: jdbc.cse.phase
    name: keyterm-extractor
    option-timeout: 2
    options: |
      - inherit: bioqa.keyterm.default

  - inherit: jdbc.cse.phase
    option-timeout: 2
    name: pos-tagger
    options: |
      - inherit: bioqa.keyterm.pos.lingpipe-hmm

  - inherit: jdbc.cse.phase
    option-timeout: 2
    name: name-entity-recognizer
    options: |
      - inherit: bioqa.keyterm.ner.lingpipe-acronym
      - inherit: bioqa.keyterm.ner.lingpipe

  - inherit: jdbc.cse.phase
    option-timeout: 2
    name: acrynom-longform-resolver
    options: |
      - inherit: bioqa.keyterm.ner.acronym-longform

  - inherit: jdbc.cse.phase
    option-timeout: 2
    name: lexical-variants-resolver
    options: |
      - inherit: bioqa.keyterm.ner.lexical-variants

  - inherit: jdbc.cse.phase
    option-timeout: 2
    name: mesh-synonyms
    options: |
      - inherit: bioqa.keyterm.kb.mesh

  - inherit: jdbc.cse.phase
    option-timeout: 2
    name: entrezgene-synonyms
    options: |
      - inherit: bioqa.keyterm.kb.entrezgene

  - inherit: jdbc.cse.phase
    option-timeout: 2
    name: umls-synonyms
    options: |
      - inherit: bioqa.keyterm.kb.umls

  - inherit: jdbc.cse.phase
    option-timeout: 2
    name: keyterm-refiner
    lazy-load-options: true
    options: |
      - inherit: bioqa.keyterm.kb.keyterm-refiner

  - inherit: jdbc.cse.phase
    name: retrieval-strategist
    option-timeout: 8
    options: |
      - inherit: bioqa.retrieval.indri

  - inherit: jdbc.cse.phase
    name: passage-extractor
    option-timeout: 8
    options: |
      - inherit: bioqa.ie.default
      - inherit: bioqa.ie.indri-legalspan

  - inherit: jdbc.cse.phase
    name: passage-span
    option-timeout: 5
    lazy-load-options: true
    options: |
      - inherit: bioqa.ie.span.important-sentence
      - inherit: base.noop

  - inherit: jdbc.cse.phase
    name: passage-rank
    option-timeout: 5
    lazy-load-options: true
    options: |
      - inherit: bioqa.ie.rank.proximity
      - inherit: base.noop

  - inherit: jdbc.cse.phase 
    name: score-combine
    option-timeout: 5
    options: |
      - inherit: bioqa.ie.rank.combine
      - inherit: base.noop

  - inherit: jdbc.cse.phase
    name: passage-overlap
    option-timeout: 5
    options: |
      - inherit: bioqa.ie.overlap.filter
      - inherit: base.noop

  - inherit: jdbc.eval.retrieval-aggregator-consumer
  - inherit: bioqa.eval.passage-map-aggregator-consumer

post-process:
  - inherit: jdbc.eval.retrieval-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: jdbc.report.f-measure-report-component
  - inherit: bioqa.eval.passage-map-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: bioqa.report.map-report-component
